services:
  app:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./data/config:/etc/odoo
      - ./data/addons:/mnt/extra-addons
    restart: unless-stopped
  
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
